runtime: custom
vm: true

network:
        forwarded_ports:
                - 65080
        instance_tag: websocket

automatic_scaling:
        min_num_instances: 1

# beta_settings:
        # Enable Google Cloud Endpoints API management
        # use_endpoints_api_management: true

        # Specify Swagger API specification document location
        # endpoints_swagger_spec_file: swagger.yaml


env_variables:
        GCLOUD_DATASET_ID: 'strong-moose'
