runtime: custom
env: flex
service: drawings

automatic_scaling:
        min_num_instances: 1

env_variables:
        GCLOUD_PROJECT_ID: 'strong-moose'
        UPSTREAM_DRAWING_TOPIC: 'incoming-drawing'
